# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: #
    weight: 10
  - name: Team
    url: team
    weight: 20
  - name: Background
    url: background
    weight: 30
  - name: Research and Applications
    url: research
    weight: 40
  - name: Collaboration and Service
    url: collaboration
    weight: 60
  - name: Publications
    url: https://www.ncbi.nlm.nih.gov/myncbi/hong.moulton.2/bibliography/public/
    weight: 65
  - name: Contact
    url: contact
    weight: 70
